#!/usr/bin/env bash
# Regenerates deploy/prometheus/rules.yml from the Terraform observability
# module, which is the source of truth.
#
# Run after changing an alert. CI checks the two are in step — an alert that
# exists only in production is one nobody has ever watched fire.
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - <<'PY'
import re, yaml
src = open('infra/terraform/modules/observability/main.tf').read()
body = re.search(r'data = <<-YAML\n(.*?)\n  YAML', src, re.S).group(1)
rules = yaml.safe_load(body)
header = (
"# Alerting rules, mirrored from infra/terraform/modules/observability/main.tf.\n"
"#\n"
"# Generated by scripts/sync-alerts.sh — do not edit by hand. Terraform is the\n"
"# source of truth; this copy exists so the same alerts can be seen firing\n"
"# locally. An alert that only exists in production is one nobody has watched.\n"
)
open('deploy/prometheus/rules.yml','w').write(header + yaml.safe_dump(rules, sort_keys=False, width=100))
print(f"synced {sum(len(g['rules']) for g in rules['groups'])} alerts")
PY
